Algoritmo "Condicional ENQUANTO"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Vinicius 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Gabriel da Silva Bispo
// Data atual  : 04/08/2026
Var
// Seção de Declarações das variáveis 
x,z,i: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Algoritmo para repetir uma ação 5 vezes")
escreval("Para cada ações, digite um numero inteiro")
escreval("")
escreval("Digite um valor inteiro")
leia(x)
i<-1
enquanto(i<=5)faca
z<-x * 3
escreval(z)
i<-i + 1
fimenquanto
Fimalgoritmo