Algoritmo "condicional PARA"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Vinicius 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Gabriel da Silva Bispo
// Data atual  : 04/08/2026
Var
// Seção de Declarações das variáveis 
x,z,i: inteiro    // aqui declaramos nossas variaveis
                  // a variavel "i" será o nosso contador

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Algoritmo para repetir uma ação 5 vezes")
escreval("Para cada ações, digite um numero inteiro")
escreval("")
escreval("Digite um valor inteiro")
para i de 1 ate 5 faca   // "i" é o contador, onde definimos a quantidade de
                         // de vezes em que ele é repetido até que
                         // satisfaça a condição estabelecida

leia(X)
z <-x*3
escreval("O valor digitado ",x," multiplicado por 3 é:",z)
fimpara

Fimalgoritmo