Algoritmo "dados da vendas"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 19/06/2026
Var
// Seção de Declarações das variáveis 
nomeCliente, nomeVendedor: caractere
   valorCompra, valorComissao: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreva("Nome do cliente: ")
   leia(nomeCliente)

   escreva("Nome do vendedor: ")
   leia(nomeVendedor)

   escreva("Valor da compra: ")
   leia(valorCompra)

   escreval("")
   escreval("--- Dados registrados ---")
   escreval("Cliente: ", nomeCliente)
   escreval("Vendedor: ", nomeVendedor)
   escreval("Valor da compra: R$ ", valorCompra)

Fimalgoritmo