Algoritmo "escolha-caso"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Vinicius 
// Descrição   : escolher o dia da semana
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/07/2026
Var
// Seção de Declarações das variáveis 
diadasemana:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite um numero entre 1 a 7 para saber o dia da semana")
leia(diadasemana)
escolha diadasemana

caso 1
escreval("domingo")

caso 2
escreval("segunda-feira")

caso 3
escreval("terça-feira")

caso 4
escreval("quarta-feira")

caso 5
escreval("quinta-feira")

caso 6
escreval("sexta-feira")

caso 7
escreval("sabado")

outrocaso
escreval("Você digitou um valor invalido")

fimescolha



Fimalgoritmo