Algoritmo "Estação do ano"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Vinicius 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/07/2026
Var
// Seção de Declarações das variáveis 
estacao: caracter

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite a estação do ano: ")
leia(estacao)

se (estacao = "primavera") ou (estacao = "verão") entao
escreval("PRAIA LIBERADA")
senao
escreval("FIQUE EM CASA")
fimse

Fimalgoritmo