Algoritmo "quadrado e cubo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Vinicius 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Gabriel da Silva Bispo
// Data atual  : 30/07/2026
Var
// Seção de Declarações das variáveis 
numero,quadrado,cubo: real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite um numero inteiro: ")
leia(numero)

quadrado <- numero ^ 2
cubo <- numero ^ 3

escreval("O quadrado de ", numero, "e: ", quadrado)
escreval("O cubo de " ,numero, "e: ",cubo)

Fimalgoritmo