Algoritmo "Verifica numero entre 20 e 90"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Vinicius 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Gabriel da Silva Bispo
// Data atual  : 30/07/2026
Var
// Seção de Declarações das variáveis 
numero: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval("Digite um numero: ")
leia(numero)

se(numero > 20) e (numero < 90) entao
escreval("O numero digitado esta entre 20 e 90 ")
senao
escreval("O valor digitado não esta entre 20 e 90 ")
fimse

Fimalgoritmo