Algoritmo "verificar_PAR"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Vinicius 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/08/2026
Var
// Seção de Declarações das variáveis 
numero:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite um número inteiro")
leia(numero)


//Verificar se é par ou impar usando o MOD(resto da divisão)
se (numero % 2=0) entao
escreval("O número ",numero," é par")
senao
escreval("O número ",numero," é ímpar")
fimse

Fimalgoritmo