Algoritmo "Vetor"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Vinicius 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Gabriel da Silva Bispo
// Data atual  : 05/08/2026
Var
// Seção de Declarações das variáveis 
vet:vetor[0..2] de real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite um número:")
leia(vet[0])
escreval("Digite um número:")
leia(vet[1])
escreval("Digite um número:")
leia(vet[2])
escreval("")
escreval("Os números digitados foram:",vet[0],vet[1],vet[2])
Fimalgoritmo