Algoritmo "expressão numerica"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Vinicius
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Gabriel Da Silva Bispo
// Data atual  : 19/06/2026
Var
// Seção de Declarações das variáveis 
num1, num2, result: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
//Bloco de Dados
num1 <- 2
num2 <- 3

//Processamento dos Dados
result <- ((num1 + num2) * (num1 - num2) ) / 4

//Saida dos Dados
escreval("O resultado da expressão numerica é: ",result)

Fimalgoritmo