Algoritmo "Media dos resultados"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 18/06/2026
Var
// Seção de Declarações das variáveis 
media, valor1, valor2, valor3, valor4:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite o primeiro valor")
leia (valor1)
escreval("Digite o segundo valor")
leia (valor2)
escreval("Digite o terceiro valor")
leia (valor3)
escreval("Digite o quarto valor")
leia (valor4)

resultado <- (valor1 + valor2 + valor3 + valor4) /4

escreval("A Media é ",media)

Fimalgoritmo