Algoritmo "somar dois valores"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Vinicius  Monteiro
// Descrição   : Algoritmo para somar dois valores
// Autor(a)    : Gabriel Da Silva Bispo
// Data atual  : 18/06/2026
Var
// Seção de Declarações das variáveis 
 resultado, valor1, valor2:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite o primeiro valor")
leia (valor1)
escreval("Digite o segundo valor")
leia (valor2)

resultado <- valor1 + valor2

escreval("O resultado soma dos valores é ",resultado)

Fimalgoritmo